---
title: '&#39;捕获&#39;永远不会到达块后，因为&#39; &lt;name1&gt; &#39;继承自&#39; &lt;name2&gt;&#39;'
ms.date: 07/20/2015
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords:
- BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
ms.openlocfilehash: 35ca615dd8fc7bbc0b2d1ae0039e9f2e70e05df6
ms.sourcegitcommit: 2eceb05f1a5bb261291a1f6a91c5153727ac1c19
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 09/04/2018
ms.locfileid: "43510547"
---
# <a name="39catch39-block-never-reached-because-39ltname1gt39-inherits-from-39ltname2gt39"></a>&#39;捕获&#39;永远不会到达块后，因为&#39; &lt;name1&gt; &#39;继承自&#39; &lt;name2&gt;&#39;
从未到达代码中的 `Catch` 块。  
  
 默认情况下，此消息是一个警告。 有关隐藏警告或将警告视为错误的详细信息，请参阅[Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic)。  
  
 **错误 ID：** BC42029  
  
## <a name="to-correct-this-error"></a>更正此错误  
  
-   删除无关的 `Catch` 块。  
  
## <a name="see-also"></a>请参阅  
 [如何： 使用 Try 测试代码...在 Visual Basic 中捕获块](https://msdn.microsoft.com/library/8368e205-ed73-4185-a247-af84fb4fafa9)  
 [Try...Catch...Finally 语句](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
