---
title: try-catch-finally（C# 参考）
ms.date: 07/20/2015
f1_keywords:
- catch-finally_CSharpKeyword
- catch-finally
helpviewer_keywords:
- finally blocks [C#]
- try-catch statement [C#]
ms.assetid: a1b443b0-ff7a-43ab-b835-0cc9bfbd15ca
ms.openlocfilehash: b60a1e17f02d7a04b782c661f2b99a28403997eb
ms.sourcegitcommit: 2eceb05f1a5bb261291a1f6a91c5153727ac1c19
ms.translationtype: HT
ms.contentlocale: zh-CN
ms.lasthandoff: 09/04/2018
ms.locfileid: "43510093"
---
# <a name="try-catch-finally-c-reference"></a>try-catch-finally（C# 参考）
`catch` 和 `finally` 的常见用法是获得并使用 `try` 块中的资源、处理 `catch` 块中的异常情况，以及释放 `finally` 块中的资源。  
  
 有关重新引发异常的详细信息和示例，请参阅 [try-catch](../../../csharp/language-reference/keywords/try-catch.md) 和[引发异常](../../../standard/exceptions/index.md)。 有关 `finally` 块的详细信息，请参阅 [try-finally](../../../csharp/language-reference/keywords/try-finally.md)。  
  
## <a name="example"></a>示例  
 [!code-csharp[csrefKeywordsExceptions#1](../../../csharp/language-reference/keywords/codesnippet/CSharp/try-catch-finally_1.cs)]  
  
## <a name="c-language-specification"></a>C# 语言规范  
 [!INCLUDE[CSharplangspec](~/includes/csharplangspec-md.md)]  
  
## <a name="see-also"></a>请参阅

- [C# 参考](../../../csharp/language-reference/index.md)  
- [C# 编程指南](../../../csharp/programming-guide/index.md)  
- [C# 关键字](../../../csharp/language-reference/keywords/index.md)  
- [try、throw 和 catch 语句 (C++)](/cpp/cpp/try-throw-and-catch-statements-cpp)  
- [异常处理语句](../../../csharp/language-reference/keywords/exception-handling-statements.md)  
- [throw](../../../csharp/language-reference/keywords/throw.md)  
- [如何显式引发异常](../../../standard/exceptions/how-to-explicitly-throw-exceptions.md)  
- [using 语句](../../../csharp/language-reference/keywords/using-statement.md)
